# Generated by Django 4.0.2 on 2022-02-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
